# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'login.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import sys

import mainWidget

class Login_Form(QtWidgets.QWidget):
    def setupUi(self, Form, child: mainWidget.Main_Widget):

        self.form = Form
        self.parentWidget = child

        Form.setObjectName("Form")
        Form.resize(919, 873)
        self.widget = QtWidgets.QWidget(Form)
        self.widget.setGeometry(QtCore.QRect(180, 260, 590, 420))
        self.widget.setObjectName("widget")
        self.label = QtWidgets.QLabel(self.widget)
        self.label.setGeometry(QtCore.QRect(290, 40, 260, 330))
        self.label.setStyleSheet("background-color:rgba(255, 255, 255,255);\n"
"border-radius:10px\n"
"")
        self.label.setText("")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.widget)
        self.label_2.setGeometry(QtCore.QRect(40, 25, 270, 360))
        self.label_2.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, stop:0 rgba(85,98,112,255), stop:1 rgba(255,107,107,255));\n"
"border-radius:10px\n"
"")
        self.label_2.setText("")
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.widget)
        self.label_3.setGeometry(QtCore.QRect(330, 80, 141, 41))
        font = QtGui.QFont()
        font.setFamily("Orbitron")
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("color:grba(0,0,0,200);")
        self.label_3.setObjectName("label_3")
        self.lineEditUsername = QtWidgets.QLineEdit(self.widget)
        self.lineEditUsername.setGeometry(QtCore.QRect(330, 140, 190, 40))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.lineEditUsername.setFont(font)
        self.lineEditUsername.setStyleSheet("background-color:rgba(0,0,0,0);\n"
"border: 2px solid rgba(0,0,0,0);\n"
"border-bottom-color:rgba(46,82,101,200);\n"
"color:rgb(0,0,0);\n"
"padding-bottom:7px;")
        self.lineEditUsername.setObjectName("lineEditUsername")
        self.lineEditpassword = QtWidgets.QLineEdit(self.widget)
        self.lineEditpassword.setGeometry(QtCore.QRect(330, 230, 190, 40))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.lineEditpassword.setFont(font)
        self.lineEditpassword.setStyleSheet("background-color:rgba(0,0,0,0);\n"
"border: 2px solid rgba(0,0,0,0);\n"
"border-bottom-color:rgba(46,82,101,200);\n"
"color:rgb(0,0,0);\n"
"padding-bottom:7px;")
        self.lineEditpassword.setEchoMode(QtWidgets.QLineEdit.Password)
        self.lineEditpassword.setObjectName("lineEditpassword")
        self.pushButton = QtWidgets.QPushButton(self.widget)
        self.pushButton.setGeometry(QtCore.QRect(340, 310, 170, 35))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.pushButton.setFont(font)
        self.pushButton.setStyleSheet("QPushButton#pushButton{\n"
"    background-color:rgba(85,98,112,255);\n"
"    color:rgba(255,255,255,200);\n"
"    border-radius:5px;\n"
"}\n"
"QPushButton#pushButton:pressed{\n"
"    padding-left:5px;\n"
"    padding-top:5px;\n"
"    background-color:rgba(255,107,107,255);\n"
"    background-position:calc(100% - 10px)center;\n"
"}\n"
"QPushButton#pushButton:hover{\n"
"    background-color:rgba(255,107,107,255);\n"
"}")
        self.pushButton.setObjectName("pushButton")
        self.label_4 = QtWidgets.QLabel(self.widget)
        self.label_4.setGeometry(QtCore.QRect(80, 50, 200, 60))
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("color:rgba(255,255,255,220);\n"
"")
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.widget)
        self.label_5.setGeometry(QtCore.QRect(80, 150, 191, 16))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_5.setFont(font)
        self.label_5.setStyleSheet("color:rgba(255,255,255,220);")
        self.label_5.setObjectName("label_5")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):

        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label_3.setText(_translate("Form", "Log In"))
        self.lineEditUsername.setPlaceholderText(_translate("Form", "Username"))
        self.lineEditpassword.setPlaceholderText(_translate("Form", "Password"))
        self.pushButton.setText(_translate("Form", "LogIn"))
        self.label_4.setText(_translate("Form", "Linux/Unix\n"
"Shell Project"))
        self.label_5.setText(_translate("Form", "Submitted by: Niv Eliyahu"))


    @QtCore.pyqtSlot()
    def on_click(self):
        self.form.hide()  # Hide the main window
        print("login was clicked")
        self.parentWidget.show()
        #self.parentWidget().show()
