# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainWidget.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtCore import QPoint, Qt


class Main_Widget(QtWidgets.QWidget):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1107, 732)
        self.widget = QtWidgets.QWidget(Form)
        self.setWindowTitle("Niv Eliyahu")
        self.widget.setGeometry(QtCore.QRect(130, 100, 921, 500))
        self.drag_start_position = None
        self.widget.setObjectName("widget")
        self.labelBackground = QtWidgets.QLabel(self.widget)
        self.labelBackground.setGeometry(QtCore.QRect(10, 10, 900, 480))
        self.labelBackground.setStyleSheet("background-color:rgba(59, 64, 69, 1);\n"
                                           "border-radius:10px\n"
                                           "")
        self.labelBackground.setText("")
        self.labelBackground.setObjectName("labelBackground")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.widget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(620, 40, 271, 431))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout_terminal = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout_terminal.setSizeConstraint(QtWidgets.QLayout.SetNoConstraint)
        self.verticalLayout_terminal.setContentsMargins(0, 10, 0, 0)
        self.verticalLayout_terminal.setSpacing(5)
        self.verticalLayout_terminal.setObjectName("verticalLayout_terminal")
        self.labelTerminal = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Orbitron")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.labelTerminal.setFont(font)
        self.labelTerminal.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.labelTerminal.setObjectName("labelTerminal")
        self.verticalLayout_terminal.addWidget(self.labelTerminal)
        self.textBrowser_terminal = QtWidgets.QTextBrowser(self.verticalLayoutWidget)
        self.textBrowser_terminal.setStyleSheet("    border-radius:10px;\n"
                                                "    border: 1px solid #000000;\n"
                                                "    background: #D9D9D9;")
        self.textBrowser_terminal.setObjectName("textBrowser_terminal")
        self.verticalLayout_terminal.addWidget(self.textBrowser_terminal)
        self.pushButton_clear = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.pushButton_clear.setEnabled(True)
        self.pushButton_clear.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.pushButton_clear.setStyleSheet("QPushButton#pushButton{\n"
                                            "    background-color:rgba(85,98,112,255);\n"
                                            "    color:rgba(255,255,255,200);\n"
                                            "    border-radius:2px;\n"
                                            "}\n"
                                            "QPushButton#pushButton:pressed{\n"
                                            "    padding-left:5px;\n"
                                            "    padding-top:5px;\n"
                                            "    background-color:rgba(255,107,107,255);\n"
                                            "    background-position:calc(100% - 10px)center;\n"
                                            "}\n"
                                            "QPushButton#pushButton:hover{\n"
                                            "    background-color:rgba(255,107,107,255);\n"
                                            "}")
        self.pushButton_clear.setIconSize(QtCore.QSize(40, 20))
        self.pushButton_clear.setObjectName("pushButton_clear")
        self.verticalLayout_terminal.addWidget(self.pushButton_clear)
        self.stackedWidget_commands_buttons = QtWidgets.QStackedWidget(self.widget)
        self.stackedWidget_commands_buttons.setGeometry(QtCore.QRect(30, 69, 181, 401))
        self.stackedWidget_commands_buttons.setObjectName("stackedWidget_commands_buttons")
        self.page_shell = QtWidgets.QWidget()
        self.page_shell.setObjectName("page_shell")
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(self.page_shell)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(9, 10, 161, 382))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.verticalLayout_Shell_commands = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_Shell_commands.setSizeConstraint(QtWidgets.QLayout.SetMinimumSize)
        self.verticalLayout_Shell_commands.setContentsMargins(0, 0, 0, 200)
        self.verticalLayout_Shell_commands.setSpacing(5)
        self.verticalLayout_Shell_commands.setObjectName("verticalLayout_Shell_commands")
        self.pushButton_ls = QtWidgets.QPushButton(self.verticalLayoutWidget_2)
        self.pushButton_ls.setStyleSheet("QPushButton#pushButton_ls{\n"
                                         "    background-color:rgba(150,150,150,1);\n"
                                         "    color:rgba(1,1,1,1);\n"
                                         "    border-color:rgba(1,1,1,1);\n"
                                         "}\n"
                                         "QPushButton#pushButton_ls:pressed{\n"
                                         "    font-weight: bold;\n"
                                         "    background-color:rgba(125,125,125,1);\n"
                                         "    color:rgba(1,1,1,1);\n"
                                         "    border-color:rgba(1,1,1,1);\n"
                                         "}\n"
                                         "QPushButton#pushButton_ls:hover{\n"
                                         "    font-weight: bold;\n"
                                         "    background-color:rgba(125,125,125,1);\n"
                                         "    color:rgba(1,1,1,1);\n"
                                         "    border-color:rgba(1,1,1,1);\n"
                                         "}")
        self.pushButton_ls.setObjectName("pushButton_ls")
        self.verticalLayout_Shell_commands.addWidget(self.pushButton_ls)
        self.pushButton_mkdir = QtWidgets.QPushButton(self.verticalLayoutWidget_2)
        self.pushButton_mkdir.setStyleSheet("QPushButton#pushButton_mkdir{\n"
                                            "    background-color:rgba(150,150,150,1);\n"
                                            "    color:rgba(1,1,1,1);\n"
                                            "    border-color:rgba(1,1,1,1);\n"
                                            "}\n"
                                            "QPushButton#pushButton_mkdir:pressed{\n"
                                            "    font-weight: bold;\n"
                                            "    background-color:rgba(125,125,125,1);\n"
                                            "    color:rgba(1,1,1,1);\n"
                                            "    border-color:rgba(1,1,1,1);\n"
                                            "}\n"
                                            "QPushButton#pushButton_mkdir:hover{\n"
                                            "    font-weight: bold;\n"
                                            "    background-color:rgba(125,125,125,1);\n"
                                            "    color:rgba(1,1,1,1);\n"
                                            "    border-color:rgba(1,1,1,1);\n"
                                            "}")
        self.pushButton_mkdir.setObjectName("pushButton_mkdir")
        self.verticalLayout_Shell_commands.addWidget(self.pushButton_mkdir)
        self.pushButton_mv = QtWidgets.QPushButton(self.verticalLayoutWidget_2)
        self.pushButton_mv.setStyleSheet("QPushButton#pushButton_mv{\n"
                                         "    background-color:rgba(150,150,150,1);\n"
                                         "    color:rgba(1,1,1,1);\n"
                                         "    border-color:rgba(1,1,1,1);\n"
                                         "}\n"
                                         "QPushButton#pushButton_mv:pressed{\n"
                                         "    font-weight: bold;\n"
                                         "    background-color:rgba(125,125,125,1);\n"
                                         "    color:rgba(1,1,1,1);\n"
                                         "    border-color:rgba(1,1,1,1);\n"
                                         "}\n"
                                         "QPushButton#pushButton_mv:hover{\n"
                                         "    font-weight: bold;\n"
                                         "    background-color:rgba(125,125,125,1);\n"
                                         "    color:rgba(1,1,1,1);\n"
                                         "    border-color:rgba(1,1,1,1);\n"
                                         "}")
        self.pushButton_mv.setObjectName("pushButton_mv")
        self.verticalLayout_Shell_commands.addWidget(self.pushButton_mv)
        self.pushButton_tail = QtWidgets.QPushButton(self.verticalLayoutWidget_2)
        self.pushButton_tail.setStyleSheet("QPushButton#pushButton_tail{\n"
                                           "    background-color:rgba(150,150,150,1);\n"
                                           "    color:rgba(1,1,1,1);\n"
                                           "    border-color:rgba(1,1,1,1);\n"
                                           "}\n"
                                           "QPushButton#pushButton_tail:pressed{\n"
                                           "    font-weight: bold;\n"
                                           "    background-color:rgba(125,125,125,1);\n"
                                           "    color:rgba(1,1,1,1);\n"
                                           "    border-color:rgba(1,1,1,1);\n"
                                           "}\n"
                                           "QPushButton#pushButton_tail:hover{\n"
                                           "    font-weight: bold;\n"
                                           "    background-color:rgba(125,125,125,1);\n"
                                           "    color:rgba(1,1,1,1);\n"
                                           "    border-color:rgba(1,1,1,1);\n"
                                           "}")
        self.pushButton_tail.setObjectName("pushButton_tail")
        self.verticalLayout_Shell_commands.addWidget(self.pushButton_tail)
        self.pushButton_wc = QtWidgets.QPushButton(self.verticalLayoutWidget_2)
        self.pushButton_wc.setStyleSheet("QPushButton#pushButton_wc{\n"
                                         "    background-color:rgba(150,150,150,1);\n"
                                         "    color:rgba(1,1,1,1);\n"
                                         "    border-color:rgba(1,1,1,1);\n"
                                         "}\n"
                                         "QPushButton#pushButton_wc:pressed{\n"
                                         "    font-weight: bold;\n"
                                         "    background-color:rgba(125,125,125,1);\n"
                                         "    color:rgba(1,1,1,1);\n"
                                         "    border-color:rgba(1,1,1,1);\n"
                                         "}\n"
                                         "QPushButton#pushButton_wc:hover{\n"
                                         "    font-weight: bold;\n"
                                         "    background-color:rgba(125,125,125,1);\n"
                                         "    color:rgba(1,1,1,1);\n"
                                         "    border-color:rgba(1,1,1,1);\n"
                                         "}")
        self.pushButton_wc.setObjectName("pushButton_wc")
        self.verticalLayout_Shell_commands.addWidget(self.pushButton_wc)
        self.stackedWidget_commands_buttons.addWidget(self.page_shell)
        self.page_admin = QtWidgets.QWidget()
        self.page_admin.setObjectName("page_admin")
        self.verticalLayoutWidget_3 = QtWidgets.QWidget(self.page_admin)
        self.verticalLayoutWidget_3.setGeometry(QtCore.QRect(10, 10, 161, 381))
        self.verticalLayoutWidget_3.setObjectName("verticalLayoutWidget_3")
        self.verticalLayout_Shell_commands_2 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_3)
        self.verticalLayout_Shell_commands_2.setSizeConstraint(QtWidgets.QLayout.SetNoConstraint)
        self.verticalLayout_Shell_commands_2.setContentsMargins(0, 0, 0, 280)
        self.verticalLayout_Shell_commands_2.setSpacing(5)
        self.verticalLayout_Shell_commands_2.setObjectName("verticalLayout_Shell_commands_2")
        self.pushButton_adduser = QtWidgets.QPushButton(self.verticalLayoutWidget_3)
        self.pushButton_adduser.setStyleSheet("QPushButton#pushButton_adduser{\n"
                                              "    background-color:rgba(150,150,150,1);\n"
                                              "    color:rgba(1,1,1,1);\n"
                                              "    border-color:rgba(1,1,1,1);\n"
                                              "\n"
                                              "}\n"
                                              "QPushButton#pushButton_adduser:pressed{\n"
                                              "    font-weight: bold;\n"
                                              "    background-color:rgba(125,125,125,1);\n"
                                              "    color:rgba(1,1,1,1);\n"
                                              "    border-color:rgba(1,1,1,1);\n"
                                              "}\n"
                                              "QPushButton#pushButton_adduser:hover{\n"
                                              "    font-weight: bold;\n"
                                              "    background-color:rgba(125,125,125,1);\n"
                                              "    color:rgba(1,1,1,1);\n"
                                              "    border-color:rgba(1,1,1,1);\n"
                                              "}")
        self.pushButton_adduser.setObjectName("pushButton_adduser")
        self.verticalLayout_Shell_commands_2.addWidget(self.pushButton_adduser)
        self.pushButton_addgroup = QtWidgets.QPushButton(self.verticalLayoutWidget_3)
        self.pushButton_addgroup.setStyleSheet("QPushButton#pushButton_addgroup{\n"
                                               "    background-color:rgba(150,150,150,1);\n"
                                               "    color:rgba(1,1,1,1);\n"
                                               "    border-color:rgba(1,1,1,1);\n"
                                               "}\n"
                                               "QPushButton#pushButton_addgroup:pressed{\n"
                                               "    font-weight: bold;\n"
                                               "    background-color:rgba(125,125,125,1);\n"
                                               "    color:rgba(1,1,1,1);\n"
                                               "    border-color:rgba(1,1,1,1);\n"
                                               "}\n"
                                               "QPushButton#pushButton_addgroup:hover{\n"
                                               "    font-weight: bold;\n"
                                               "    background-color:rgba(125,125,125,1);\n"
                                               "    color:rgba(1,1,1,1);\n"
                                               "    border-color:rgba(1,1,1,1);\n"
                                               "}")
        self.pushButton_addgroup.setObjectName("pushButton_addgroup")
        self.verticalLayout_Shell_commands_2.addWidget(self.pushButton_addgroup)
        self.pushButton_changepass = QtWidgets.QPushButton(self.verticalLayoutWidget_3)
        self.pushButton_changepass.setStyleSheet("QPushButton#pushButton_changepass{\n"
                                                 "    background-color:rgba(150,150,150,1);\n"
                                                 "    color:rgba(1,1,1,1);\n"
                                                 "    border-color:rgba(1,1,1,1);\n"
                                                 "\n"
                                                 "}\n"
                                                 "QPushButton#pushButton_changepass:pressed{\n"
                                                 "    font-weight: bold;\n"
                                                 "    background-color:rgba(125,125,125,1);\n"
                                                 "    color:rgba(1,1,1,1);\n"
                                                 "    border-color:rgba(1,1,1,1);\n"
                                                 "}\n"
                                                 "QPushButton#pushButton_changepass:hover{\n"
                                                 "    font-weight: bold;\n"
                                                 "    background-color:rgba(125,125,125,1);\n"
                                                 "    color:rgba(1,1,1,1);\n"
                                                 "    border-color:rgba(1,1,1,1);\n"
                                                 "}")
        self.pushButton_changepass.setObjectName("pushButton_changepass")
        self.verticalLayout_Shell_commands_2.addWidget(self.pushButton_changepass)
        self.stackedWidget_commands_buttons.addWidget(self.page_admin)
        self.page_system = QtWidgets.QWidget()
        self.page_system.setObjectName("page_system")
        self.verticalLayoutWidget_4 = QtWidgets.QWidget(self.page_system)
        self.verticalLayoutWidget_4.setGeometry(QtCore.QRect(10, 10, 161, 381))
        self.verticalLayoutWidget_4.setObjectName("verticalLayoutWidget_4")
        self.verticalLayout_Shell_commands_4 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_4)
        self.verticalLayout_Shell_commands_4.setSizeConstraint(QtWidgets.QLayout.SetMinimumSize)
        self.verticalLayout_Shell_commands_4.setContentsMargins(0, 0, 0, 280)
        self.verticalLayout_Shell_commands_4.setSpacing(5)
        self.verticalLayout_Shell_commands_4.setObjectName("verticalLayout_Shell_commands_4")
        self.pushButton_kill = QtWidgets.QPushButton(self.verticalLayoutWidget_4)
        self.pushButton_kill.setStyleSheet("QPushButton#pushButton_kill{\n"
                                           "    background-color:rgba(150,150,150,1);\n"
                                           "    color:rgba(1,1,1,1);\n"
                                           "    border-color:rgba(1,1,1,1);\n"
                                           "}\n"
                                           "QPushButton#pushButton_kill:pressed{\n"
                                           "    font-weight: bold;\n"
                                           "    background-color:rgba(125,125,125,1);\n"
                                           "    color:rgba(1,1,1,1);\n"
                                           "    border-color:rgba(1,1,1,1);\n"
                                           "}\n"
                                           "QPushButton#pushButton_kill:hover{\n"
                                           "    font-weight: bold;\n"
                                           "    background-color:rgba(125,125,125,1);\n"
                                           "    color:rgba(1,1,1,1);\n"
                                           "    border-color:rgba(1,1,1,1);\n"
                                           "}")
        self.pushButton_kill.setObjectName("pushButton_kill")
        self.verticalLayout_Shell_commands_4.addWidget(self.pushButton_kill)
        self.pushButton_ps = QtWidgets.QPushButton(self.verticalLayoutWidget_4)
        self.pushButton_ps.setStyleSheet("QPushButton#pushButton_ps{\n"
                                         "    background-color:rgba(150,150,150,1);\n"
                                         "    color:rgba(1,1,1,1);\n"
                                         "    border-color:rgba(1,1,1,1);\n"
                                         "}\n"
                                         "QPushButton#pushButton_ps:pressed{\n"
                                         "    font-weight: bold;\n"
                                         "    background-color:rgba(125,125,125,1);\n"
                                         "    color:rgba(1,1,1,1);\n"
                                         "    border-color:rgba(1,1,1,1);\n"
                                         "}\n"
                                         "QPushButton#pushButton_ps:hover{\n"
                                         "    font-weight: bold;\n"
                                         "    background-color:rgba(125,125,125,1);\n"
                                         "    color:rgba(1,1,1,1);\n"
                                         "    border-color:rgba(1,1,1,1);\n"
                                         "}")
        self.pushButton_ps.setObjectName("pushButton_ps")
        self.verticalLayout_Shell_commands_4.addWidget(self.pushButton_ps)
        self.pushButton_whoami = QtWidgets.QPushButton(self.verticalLayoutWidget_4)
        self.pushButton_whoami.setStyleSheet("QPushButton#pushButton_whoami{\n"
                                             "    background-color:rgba(150,150,150,1);\n"
                                             "    color:rgba(1,1,1,1);\n"
                                             "    border-color:rgba(1,1,1,1);\n"
                                             "}\n"
                                             "QPushButton#pushButton_whoami:pressed{\n"
                                             "    font-weight: bold;\n"
                                             "    background-color:rgba(125,125,125,1);\n"
                                             "    color:rgba(1,1,1,1);\n"
                                             "    border-color:rgba(1,1,1,1);\n"
                                             "}\n"
                                             "QPushButton#pushButton_whoami:hover{\n"
                                             "    font-weight: bold;\n"
                                             "    background-color:rgba(125,125,125,1);\n"
                                             "    color:rgba(1,1,1,1);\n"
                                             "    border-color:rgba(1,1,1,1);\n"
                                             "}")
        self.pushButton_whoami.setObjectName("pushButton_whoami")
        self.verticalLayout_Shell_commands_4.addWidget(self.pushButton_whoami)
        self.stackedWidget_commands_buttons.addWidget(self.page_system)
        self.stackedWidget_commands = QtWidgets.QStackedWidget(self.widget)
        self.stackedWidget_commands.setGeometry(QtCore.QRect(219, 70, 391, 401))
        self.stackedWidget_commands.setObjectName("stackedWidget_commands")
        self.page_ls = QtWidgets.QWidget()
        self.page_ls.setObjectName("page_ls")
        self.gridLayoutWidget_2 = QtWidgets.QWidget(self.page_ls)
        self.gridLayoutWidget_2.setGeometry(QtCore.QRect(20, 20, 351, 71))
        self.gridLayoutWidget_2.setObjectName("gridLayoutWidget_2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.gridLayoutWidget_2)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_src_2 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label_src_2.setObjectName("label_src_2")
        self.gridLayout_2.addWidget(self.label_src_2, 0, 0, 1, 1)
        self.lineEdit_ls = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        self.lineEdit_ls.setObjectName("lineEdit_ls")
        self.gridLayout_2.addWidget(self.lineEdit_ls, 0, 1, 1, 1)
        self.pushButton_ls_browse_ = QtWidgets.QPushButton(self.gridLayoutWidget_2)
        self.pushButton_ls_browse_.setObjectName("pushButton_ls_browse_")
        self.gridLayout_2.addWidget(self.pushButton_ls_browse_, 0, 2, 1, 1)
        self.pushButton_ls_exe = QtWidgets.QPushButton(self.page_ls)
        self.pushButton_ls_exe.setGeometry(QtCore.QRect(60, 350, 290, 28))
        self.pushButton_ls_exe.setObjectName("pushButton_ls_exe")
        self.comboBox_ls = QtWidgets.QComboBox(self.page_ls)
        self.comboBox_ls.setGeometry(QtCore.QRect(130, 140, 111, 22))
        self.comboBox_ls.setObjectName("comboBox_ls")
        self.comboBox_ls.addItem("")
        self.comboBox_ls.addItem("")
        self.comboBox_ls.addItem("")
        self.comboBox_ls.addItem("")
        self.label_ls = QtWidgets.QLabel(self.page_ls)
        self.label_ls.setGeometry(QtCore.QRect(130, 110, 121, 16))
        self.label_ls.setObjectName("label_ls")
        self.stackedWidget_commands.addWidget(self.page_ls)
        self.page_mkdir = QtWidgets.QWidget()
        self.page_mkdir.setObjectName("page_mkdir")
        self.gridLayoutWidget_3 = QtWidgets.QWidget(self.page_mkdir)
        self.gridLayoutWidget_3.setGeometry(QtCore.QRect(20, 20, 351, 121))
        self.gridLayoutWidget_3.setObjectName("gridLayoutWidget_3")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.gridLayoutWidget_3)
        self.gridLayout_5.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.label_src_5 = QtWidgets.QLabel(self.gridLayoutWidget_3)
        self.label_src_5.setObjectName("label_src_5")
        self.gridLayout_5.addWidget(self.label_src_5, 0, 0, 1, 1)
        self.pushButton_mkdir_browse = QtWidgets.QPushButton(self.gridLayoutWidget_3)
        self.pushButton_mkdir_browse.setObjectName("pushButton_mkdir_browse")
        self.gridLayout_5.addWidget(self.pushButton_mkdir_browse, 0, 2, 1, 1)
        self.lineEdit_mkdir = QtWidgets.QLineEdit(self.gridLayoutWidget_3)
        self.lineEdit_mkdir.setObjectName("lineEdit_mkdir")
        self.gridLayout_5.addWidget(self.lineEdit_mkdir, 0, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.gridLayoutWidget_3)
        self.label_2.setObjectName("label_2")
        self.gridLayout_5.addWidget(self.label_2, 1, 0, 1, 1)
        self.lineEdit_dirname = QtWidgets.QLineEdit(self.gridLayoutWidget_3)
        self.lineEdit_dirname.setObjectName("lineEdit_dirname")
        self.gridLayout_5.addWidget(self.lineEdit_dirname, 1, 1, 1, 1)
        self.pushButton_mkdir_exe = QtWidgets.QPushButton(self.page_mkdir)
        self.pushButton_mkdir_exe.setGeometry(QtCore.QRect(60, 350, 290, 28))
        self.pushButton_mkdir_exe.setObjectName("pushButton_mkdir_exe")
        self.stackedWidget_commands.addWidget(self.page_mkdir)
        self.page_mv = QtWidgets.QWidget()
        self.page_mv.setObjectName("page_mv")
        self.gridLayoutWidget = QtWidgets.QWidget(self.page_mv)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(20, 20, 351, 121))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.label_src = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_src.setObjectName("label_src")
        self.gridLayout.addWidget(self.label_src, 0, 0, 1, 1)
        self.lineEdit_mv_dest = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.lineEdit_mv_dest.setObjectName("lineEdit_mv_dest")
        self.gridLayout.addWidget(self.lineEdit_mv_dest, 1, 1, 1, 1)
        self.pushButton_mv_dest = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton_mv_dest.setObjectName("pushButton_mv_dest")
        self.gridLayout.addWidget(self.pushButton_mv_dest, 1, 2, 1, 1)
        self.pushButton_mv_src = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton_mv_src.setObjectName("pushButton_mv_src")
        self.gridLayout.addWidget(self.pushButton_mv_src, 0, 2, 1, 1)
        self.label_dest = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_dest.setObjectName("label_dest")
        self.gridLayout.addWidget(self.label_dest, 1, 0, 1, 1)
        self.lineEdit_mv_src = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.lineEdit_mv_src.setObjectName("lineEdit_mv_src")
        self.gridLayout.addWidget(self.lineEdit_mv_src, 0, 1, 1, 1)
        self.pushButton_mv_exe = QtWidgets.QPushButton(self.page_mv)
        self.pushButton_mv_exe.setGeometry(QtCore.QRect(60, 350, 290, 28))
        self.pushButton_mv_exe.setObjectName("pushButton_mv_exe")
        self.stackedWidget_commands.addWidget(self.page_mv)
        self.page_tail = QtWidgets.QWidget()
        self.page_tail.setObjectName("page_tail")
        self.gridLayoutWidget_4 = QtWidgets.QWidget(self.page_tail)
        self.gridLayoutWidget_4.setGeometry(QtCore.QRect(20, 20, 351, 71))
        self.gridLayoutWidget_4.setObjectName("gridLayoutWidget_4")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.gridLayoutWidget_4)
        self.gridLayout_6.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.label_src_6 = QtWidgets.QLabel(self.gridLayoutWidget_4)
        self.label_src_6.setObjectName("label_src_6")
        self.gridLayout_6.addWidget(self.label_src_6, 0, 0, 1, 1)
        self.lineEdit_tail = QtWidgets.QLineEdit(self.gridLayoutWidget_4)
        self.lineEdit_tail.setObjectName("lineEdit_tail")
        self.gridLayout_6.addWidget(self.lineEdit_tail, 0, 1, 1, 1)
        self.pushButton_tail_browse = QtWidgets.QPushButton(self.gridLayoutWidget_4)
        self.pushButton_tail_browse.setObjectName("pushButton_tail_browse")
        self.gridLayout_6.addWidget(self.pushButton_tail_browse, 0, 2, 1, 1)
        self.pushButton_tail_exe = QtWidgets.QPushButton(self.page_tail)
        self.pushButton_tail_exe.setGeometry(QtCore.QRect(60, 350, 290, 28))
        self.pushButton_tail_exe.setObjectName("pushButton_tail_exe")
        self.stackedWidget_commands.addWidget(self.page_tail)
        self.page_wc = QtWidgets.QWidget()
        self.page_wc.setObjectName("page_wc")
        self.gridLayoutWidget_5 = QtWidgets.QWidget(self.page_wc)
        self.gridLayoutWidget_5.setGeometry(QtCore.QRect(20, 20, 351, 71))
        self.gridLayoutWidget_5.setObjectName("gridLayoutWidget_5")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.gridLayoutWidget_5)
        self.gridLayout_7.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.label_src_7 = QtWidgets.QLabel(self.gridLayoutWidget_5)
        self.label_src_7.setObjectName("label_src_7")
        self.gridLayout_7.addWidget(self.label_src_7, 0, 0, 1, 1)
        self.lineEdit_src_wc = QtWidgets.QLineEdit(self.gridLayoutWidget_5)
        self.lineEdit_src_wc.setObjectName("lineEdit_src_wc")
        self.gridLayout_7.addWidget(self.lineEdit_src_wc, 0, 1, 1, 1)
        self.pushButton_wc_browse_ = QtWidgets.QPushButton(self.gridLayoutWidget_5)
        self.pushButton_wc_browse_.setObjectName("pushButton_wc_browse_")
        self.gridLayout_7.addWidget(self.pushButton_wc_browse_, 0, 2, 1, 1)
        self.pushButton_wc_exe = QtWidgets.QPushButton(self.page_wc)
        self.pushButton_wc_exe.setGeometry(QtCore.QRect(60, 350, 290, 28))
        self.pushButton_wc_exe.setObjectName("pushButton_wc_exe")
        self.stackedWidget_commands.addWidget(self.page_wc)
        self.page_kill = QtWidgets.QWidget()
        self.page_kill.setObjectName("page_kill")
        self.gridLayoutWidget_6 = QtWidgets.QWidget(self.page_kill)
        self.gridLayoutWidget_6.setGeometry(QtCore.QRect(20, 20, 351, 71))
        self.gridLayoutWidget_6.setObjectName("gridLayoutWidget_6")
        self.gridLayout_8 = QtWidgets.QGridLayout(self.gridLayoutWidget_6)
        self.gridLayout_8.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.label_src_8 = QtWidgets.QLabel(self.gridLayoutWidget_6)
        self.label_src_8.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_src_8.setObjectName("label_src_8")
        self.gridLayout_8.addWidget(self.label_src_8, 0, 0, 1, 1)
        self.lineEdit_src_kill = QtWidgets.QLineEdit(self.gridLayoutWidget_6)
        self.lineEdit_src_kill.setObjectName("lineEdit_src_kill")
        self.gridLayout_8.addWidget(self.lineEdit_src_kill, 0, 1, 1, 1)
        self.pushButton_kill_exc = QtWidgets.QPushButton(self.gridLayoutWidget_6)
        self.pushButton_kill_exc.setObjectName("pushButton_kill_exc")
        self.gridLayout_8.addWidget(self.pushButton_kill_exc, 0, 2, 1, 1)
        self.stackedWidget_commands.addWidget(self.page_kill)
        self.page_black = QtWidgets.QWidget()
        self.page_black.setObjectName("page_black")
        self.stackedWidget_commands.addWidget(self.page_black)
        self.lable_left_section = QtWidgets.QLabel(self.widget)
        self.lable_left_section.setGeometry(QtCore.QRect(30, 70, 181, 401))
        self.lable_left_section.setStyleSheet("background-color:rgba(217, 217, 217, 1);\n"
                                              "border-radius:10px\n"
                                              "")
        self.lable_left_section.setText("")
        self.lable_left_section.setObjectName("lable_left_section")
        self.lable_center_section = QtWidgets.QLabel(self.widget)
        self.lable_center_section.setGeometry(QtCore.QRect(220, 70, 391, 401))
        self.lable_center_section.setStyleSheet("background-color:rgba(217, 217, 217, 1);\n"
                                                "border-radius:10px\n"
                                                "")
        self.lable_center_section.setText("")
        self.lable_center_section.setObjectName("lable_center_section")
        self.pushButton_exit = QtWidgets.QPushButton(self.widget)
        self.pushButton_exit.setGeometry(QtCore.QRect(870, 20, 31, 31))
        self.pushButton_exit.setStyleSheet("QPushButton#pushButton_exit{\n"
                                           "    background-color:rgba(0,0,0,0);\n"
                                           "    color:rgba(1,1,1,1);\n"
                                           "    font: 10pt \"3DS Fonticon CID\";\n"
                                           "}\n"
                                           "QPushButton#pushButton_exit:pressed{\n"
                                           "    font: 10pt \"3DS Fonticon CID\";\n"
                                           "    font-weight: bold;\n"
                                           "    background-color:rgba(0,0,0,0);\n"
                                           "    color:rgba(255, 87, 51,1);\n"
                                           "    padding-left:5px;\n"
                                           "    padding-top:5px;\n"
                                           "    background-position:calc(100% - 10px)center;\n"
                                           "}\n"
                                           "QPushButton#pushButton_exit:hover{\n"
                                           "    font-weight: bold;\n"
                                           "    background-color:rgba(0,0,0,0);\n"
                                           "    color:rgba(255, 87, 51,1);\n"
                                           "    font: 10pt \"3DS Fonticon CID\";\n"
                                           "}")
        self.pushButton_exit.setObjectName("pushButton_exit")
        self.labelBackground.raise_()
        self.verticalLayoutWidget.raise_()
        self.lable_left_section.raise_()
        self.lable_center_section.raise_()
        self.stackedWidget_commands_buttons.raise_()
        self.stackedWidget_commands.raise_()
        self.pushButton_exit.raise_()
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(170, 60, 501, 61))
        self.label.setStyleSheet("background-color:rgba(88, 111, 134, 1);\n"
                                 "border-radius:10px\n"
                                 "")
        self.label.setText("")
        self.label.setObjectName("label")
        self.horizontalLayoutWidget = QtWidgets.QWidget(Form)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(180, 60, 485, 51))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pushButtonShell = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Orbitron")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.pushButtonShell.setFont(font)
        self.pushButtonShell.setStyleSheet("QPushButton#pushButtonShell{\n"
                                           "    background-color:rgba(0,0,0,0);\n"
                                           "    color:rgba(255,255,255,200);\n"
                                           "}\n"
                                           "QPushButton#pushButtonShell:pressed{\n"
                                           "    padding-left:5px;\n"
                                           "    padding-top:5px;\n"
                                           "    background-color:rgba(0,0,0,0);\n"
                                           "    background-position:calc(100% - 10px)center;\n"
                                           "    color:rgba(1,1,1,1);\n"
                                           "    font-weight: bold;\n"
                                           "\n"
                                           "\n"
                                           "}\n"
                                           "QPushButton#pushButtonShell:hover{\n"
                                           "    color:rgba(1,1,1,1);\n"
                                           "    font-weight: bold;\n"
                                           "\n"
                                           "}")
        self.pushButtonShell.setObjectName("pushButtonShell")
        self.horizontalLayout.addWidget(self.pushButtonShell)
        self.pushButtonAdmin = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Orbitron")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.pushButtonAdmin.setFont(font)
        self.pushButtonAdmin.setStyleSheet("QPushButton#pushButtonAdmin{\n"
                                           "    background-color:rgba(0,0,0,0);\n"
                                           "    color:rgba(255,255,255,200);\n"
                                           "}\n"
                                           "QPushButton#pushButtonAdmin:pressed{\n"
                                           "    padding-left:5px;\n"
                                           "    padding-top:5px;\n"
                                           "    background-color:rgba(0,0,0,0);\n"
                                           "    background-position:calc(100% - 10px)center;\n"
                                           "    color:rgba(1,1,1,1);\n"
                                           "    font-weight: bold;\n"
                                           "\n"
                                           "\n"
                                           "}\n"
                                           "QPushButton#pushButtonAdmin:hover{\n"
                                           "    color:rgba(1,1,1,1);\n"
                                           "    font-weight: bold;\n"
                                           "\n"
                                           "}")
        self.pushButtonAdmin.setObjectName("pushButtonAdmin")
        self.horizontalLayout.addWidget(self.pushButtonAdmin)
        self.pushButtonSystem = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Orbitron")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.pushButtonSystem.setFont(font)
        self.pushButtonSystem.setStyleSheet("QPushButton#pushButtonSystem{\n"
                                            "    background-color:rgba(0,0,0,0);\n"
                                            "    color:rgba(255,255,255,200);\n"
                                            "}\n"
                                            "QPushButton#pushButtonSystem:pressed{\n"
                                            "    padding-left:5px;\n"
                                            "    padding-top:5px;\n"
                                            "    background-color:rgba(0,0,0,0);\n"
                                            "    background-position:calc(100% - 10px)center;\n"
                                            "    color:rgba(1,1,1,1);\n"
                                            "    font-weight: bold;\n"
                                            "\n"
                                            "\n"
                                            "}\n"
                                            "QPushButton#pushButtonSystem:hover{\n"
                                            "    color:rgba(1,1,1,1);\n"
                                            "    font-weight: bold;\n"
                                            "\n"
                                            "}")
        self.pushButtonSystem.setObjectName("pushButtonSystem")
        self.horizontalLayout.addWidget(self.pushButtonSystem)
        self.label.raise_()
        self.widget.raise_()
        self.horizontalLayoutWidget.raise_()

        self.retranslateUi(Form)
        self.stackedWidget_commands_buttons.setCurrentIndex(0)
        self.stackedWidget_commands.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.labelTerminal.setText(
            _translate("Form", "<html><head/><body><p align=\"center\">Terminal</p></body></html>"))
        self.pushButton_clear.setText(_translate("Form", "Clear"))
        self.pushButton_ls.setText(_translate("Form", "ls"))
        self.pushButton_mkdir.setText(_translate("Form", "mkdir"))
        self.pushButton_mv.setText(_translate("Form", "mv"))
        self.pushButton_tail.setText(_translate("Form", "tail"))
        self.pushButton_wc.setText(_translate("Form", "wc"))
        self.pushButton_adduser.setText(_translate("Form", "add user"))
        self.pushButton_addgroup.setText(_translate("Form", "add group"))
        self.pushButton_changepass.setText(_translate("Form", "change password"))
        self.pushButton_kill.setText(_translate("Form", "kill"))
        self.pushButton_ps.setText(_translate("Form", "ps"))
        self.pushButton_whoami.setText(_translate("Form", "whoami"))
        self.label_src_2.setText(_translate("Form", "Select dir"))
        self.pushButton_ls_browse_.setText(_translate("Form", "Browse"))
        self.pushButton_ls_exe.setText(_translate("Form", "Execute"))
        self.comboBox_ls.setItemText(0, _translate("Form", "ls"))
        self.comboBox_ls.setItemText(1, _translate("Form", "ls -a"))
        self.comboBox_ls.setItemText(2, _translate("Form", "ls -l"))
        self.comboBox_ls.setItemText(3, _translate("Form", "ls -r"))
        self.label_ls.setText(_translate("Form", "Choose How to run file:"))
        self.label_src_5.setText(_translate("Form", "Select dir location"))
        self.pushButton_mkdir_browse.setText(_translate("Form", "Browse"))
        self.label_2.setText(_translate("Form", "Dir name"))
        self.pushButton_mkdir_exe.setText(_translate("Form", "Execute"))
        self.label_src.setText(_translate("Form", "Select File"))
        self.pushButton_mv_dest.setText(_translate("Form", "Browse"))
        self.pushButton_mv_src.setText(_translate("Form", "Browse"))
        self.label_dest.setText(_translate("Form", "Destination"))
        self.pushButton_mv_exe.setText(_translate("Form", "Execute"))
        self.label_src_6.setText(_translate("Form", "Select dir"))
        self.pushButton_tail_browse.setText(_translate("Form", "Browse"))
        self.pushButton_tail_exe.setText(_translate("Form", "Execute"))
        self.label_src_7.setText(_translate("Form", "Select file"))
        self.pushButton_wc_browse_.setText(_translate("Form", "Browse"))
        self.pushButton_wc_exe.setText(_translate("Form", "Execute"))
        self.label_src_8.setText(_translate("Form", "          PID       "))
        self.pushButton_kill_exc.setText(_translate("Form", "Kill"))
        self.pushButton_exit.setText(_translate("Form", ""))
        self.pushButtonShell.setText(_translate("Form", "Shell Commands"))
        self.pushButtonAdmin.setText(_translate("Form", "Admin Commands"))
        self.pushButtonSystem.setText(_translate("Form", "System Commands"))

    def mousePressEvent(self, event):
        self.__mousePressPos = None
        self.__mouseMovePos = None
        if event.button() == QtCore.Qt.LeftButton:
            self.__mousePressPos = event.globalPos()
            self.__mouseMovePos = event.globalPos()

        super(Main_Widget, self).mousePressEvent(event)

    def mouseMoveEvent(self, event):
        if event.buttons() == QtCore.Qt.LeftButton:
            # adjust offset from clicked point to origin of widget
            currPos = self.mapToGlobal(self.pos())
            globalPos = event.globalPos()
            diff = globalPos - self.__mouseMovePos
            newPos = self.mapFromGlobal(currPos + diff)
            self.move(newPos)

            self.__mouseMovePos = globalPos
            super(Main_Widget, self).mousePressEvent(event)


    def mouseReleaseEvent(self, event):
        # Reset the drag start position
        if self.__mousePressPos is not None:
            moved = event.globalPos() - self.__mousePressPos
            if moved.manhattanLength() > 3:
                event.ignore()
                return

        super(Main_Widget, self).mousePressEvent(event)

